const notes = [
  {
    id: 1,
    active: true,
    title: "React Performance Optimization",
    tags: ["Frontend", "React"],
    edited_time: "29 Oct 2024",
    content: `Key performance optimization techniques:\n\n1. Code Splitting\n2. Memoization\n3. Virtual Lists`,
  },
  {
    id: 2,
    active: false,
    title: "JavaScript Async Mastery",
    tags: ["JavaScript", "Async"],
    edited_time: "15 Nov 2024",
    content: "Callbacks, promises, and async/await explained with examples.",
  },
  {
    id: 3,
    active: false,
    title: "Node.js Backend Guide",
    tags: ["Backend", "Node.js"],
    edited_time: "5 Dec 2024",
    content: "Building REST APIs with Express.js and middleware patterns.",
  },
  {
    id: 4,
    active: false,
    title: "CSS Layout Mastery",
    tags: ["CSS", "Frontend", "Design"],
    edited_time: "10 Oct 2024",
    content: "Mastering Flexbox and Grid for responsive design.",
  },
  {
    id: 5,
    active: false,
    title: "Optimizing SQL Databases",
    tags: ["Database", "SQL", "Backend"],
    edited_time: "20 Nov 2024",
    content: "Indexing, normalization, and query optimization.",
  },
  {
    id: 6,
    active: false,
    title: "Version Control Essentials",
    tags: ["Git", "Tooling"],
    edited_time: "8 Dec 2024",
    content: "Branching, merging, rebasing, and working with remotes.",
  },
  {
    id: 7,
    active: false,
    title: "Agile Sprint Planning",
    tags: ["Project Management", "Agile"],
    edited_time: "18 Oct 2024",
    content: "User stories, sprints, retrospectives, and velocity tracking.",
  },
  {
    id: 8,
    active: false,
    title: "JavaScript Design Patterns",
    tags: ["JavaScript", "Design Patterns"],
    edited_time: "22 Nov 2024",
    content: "Singleton, Factory, and Observer pattern in JS.",
  },
  {
    id: 9,
    active: false,
    title: "Inclusive Web Design",
    tags: ["Accessibility", "Design"],
    edited_time: "30 Oct 2024",
    content: "ARIA roles, keyboard navigation, and WCAG compliance.",
  },
  {
    id: 10,
    active: false,
    title: "React Testing with Jest",
    tags: ["React", "Testing"],
    edited_time: "12 Nov 2024",
    content: "Unit and integration testing with Jest and RTL.",
  },
  // --- New notes ---
  {
    id: 11,
    active: false,
    title: "Docker Essentials",
    tags: ["DevOps", "Containers"],
    edited_time: "1 Jan 2025",
    content: "Building, running, and managing Docker containers effectively.",
  },
  {
    id: 12,
    active: false,
    title: "TypeScript Deep Dive",
    tags: ["TypeScript", "Frontend", "JavaScript"],
    edited_time: "5 Jan 2025",
    content: "Types, interfaces, generics, and advanced TypeScript patterns.",
  },
  {
    id: 13,
    active: false,
    title: "Kubernetes Introduction",
    tags: ["DevOps", "Containers", "Cloud"],
    edited_time: "10 Jan 2025",
    content: "Deploying applications and managing clusters with Kubernetes.",
  },
  {
    id: 14,
    active: false,
    title: "GraphQL APIs",
    tags: ["Backend", "API", "GraphQL"],
    edited_time: "12 Jan 2025",
    content: "Querying and mutating data using GraphQL for efficient APIs.",
  },
  {
    id: 15,
    active: false,
    title: "Next.js Server-Side Rendering",
    tags: ["React", "Next.js", "Frontend"],
    edited_time: "15 Jan 2025",
    content: "Implement SSR and SSG for optimized performance in Next.js.",
  },
  {
    id: 16,
    active: false,
    title: "Python for Data Analysis",
    tags: ["Python", "Data Science", "Pandas"],
    edited_time: "20 Jan 2025",
    content: "Using Python libraries like Pandas and NumPy to analyze data.",
  },
  {
    id: 17,
    active: false,
    title: "Machine Learning Basics",
    tags: ["ML", "Python", "AI"],
    edited_time: "25 Jan 2025",
    content:
      "Supervised and unsupervised learning, training models, and evaluation.",
  },
  {
    id: 18,
    active: false,
    title: "CSS Animations & Transitions",
    tags: ["CSS", "Frontend", "Design"],
    edited_time: "30 Jan 2025",
    content: "Animating UI elements with CSS keyframes and transitions.",
  },
  {
    id: 19,
    active: false,
    title: "REST API Best Practices",
    tags: ["Backend", "API", "Design"],
    edited_time: "5 Feb 2025",
    content: "Designing REST APIs with proper HTTP methods and status codes.",
  },
  {
    id: 20,
    active: false,
    title: "Unit Testing in Python",
    tags: ["Python", "Testing", "Backend"],
    edited_time: "10 Feb 2025",
    content: "Writing unit tests with unittest and pytest frameworks.",
  },
];

export default notes;
